### PR TITLE
Add array-swap

### PR DESCRIPTION
**Pull request by goschevski**
Add array-swap to list of array plugins.

### CODE REVIEW

**Comment by parro-it** [comment]
Hi, thank you for your suggestion: I look at the module you're suggesting, I have some concerns about it:
it extends the Array prototype, it has a poor readme and it lacks tests.
I saw you wrote a PR to this repo improving the README, awesome! 

Go ahead with it, create some tests for the module, and maybe try to extract the part in which it extends the array and make it optional. 

I will be happy to include the module when the author merge your PR.

Thank you again for the contribution

**Comment by parro-it** [comment]
ping @goschevski, ping @Marko-Jankovic

**Comment by goschevski** [comment]
Hey @parro-it, thanks. I will add tests as soon as I find time for that.
I will see with @marko-jankovic if he's interested to change implementation of the module.

**Comment by parro-it** [comment]
Don't worry, take your time. I close this for now, ping me here when you'll get news about

**Pull request closed without merging**
